# Bayesian Statistical Spam Filter Configuration

backend = "redis";
servers = "redis:6379";
autolearn = true;

# Automatic learning thresholds
autolearn {
  spam_threshold = 14.0;
  ham_threshold = -2.0;
  check_balance = true;
  min_tokens = 10;
}
