const fs = require('fs');
const path = require('path');

const booksJsonPath = path.join(__dirname, '../src/data/books.json');
const books = JSON.parse(fs.readFileSync(booksJsonPath, 'utf8'));

const longReviews = [
  "I started this with zero expectations, thinking it would just be another overhyped recommendation from my feeds. But honestly? It completely blew my mind. The writing is incredibly dense but flows with a beautiful, slow velocity that makes you want to savor every single page. The author has this unique ability to take these deeply ordinary, everyday moments and turn them into profound observations about human connection, grief, and the passing of time. It really reminded me of Camus or Orwell in how direct, honest, and quietly wise the prose remains without ever trying to moralize or tell you how to feel. There is this quiet melancholy running through the entire narrative, mapping the characters' internal struggles onto their physical surroundings so perfectly that it feels less like reading a story and more like breathing in a specific atmosphere. It's the kind of book that makes you want to immediately close your laptop, sit in silence for an hour, and just think about your own life. If you're looking for something fast-paced with quick action, this definitely isn't it; but if you want a deeply reflective, beautifully observed study of human nature that will linger in your mind for months, you absolutely have to pick this up.",
  "This was a recommendation from a close friend during a phase where I was feeling completely burnt out and overwhelmed by the constant digital noise of startup life, and I am so incredibly glad I sat down with it. It is a absolute masterclass in intentional living. Instead of offering the usual superficial productivity hacks or 'hustle harder' clichés, the author takes a step back and asks what it actually means to do meaningful, deep work in a world designed to constantly distract us. The insights are incredibly sharp and practical, but what I loved most is the philosophical undertone—it's a call to reclaim your attention, your cognitive limits, and ultimately your personal freedom from the algorithms. The writing is super conversational and down-to-earth, beneran kek ngobrolin buku directly over coffee with a wise mentor. It makes you realize that true success isn't about doing more, but about having the courage to do less, do it deeply, and choose what actually matters to you. I've highlighted almost half the pages and keep coming back to the chapters on deep focus and restorative solitude whenever I feel my attention slipping. Absolutely essential reading for anyone trying to build something real in the modern era.",
  "Wow, what an absolutely incredible ride. I finished this in two sittings because the narrative has this crazy, magnetic velocity that just pulls you in and doesn't let go. The author writes with so much structural confidence and wit, balancing really complex psychological tensions with crisp, hilarious dialogue and profound observations about modern society. It's a brilliant piece of narrative architecture that captures the sheer absurdity and beauty of trying to create something authentic today. What really hit home for me was the exploration of personal agency—how easy it is to fall into social conditioning and comfortable routines, and how much courage it actually takes to step out of that and choose your own path. It's wise, sharp, and incredibly smart, but delivered in a way that feels totally casual and unpretentious, beneran kek nongkrong bareng temen cerdas yang lagi cerita seru. There are no dry lectures or lazy tropes here, just an honest, beautifully crafted mirror held up to our daily struggles and desires. It's rare to find a book that is both intellectually stimulating and genuinely fun to read, but this one hits the sweet spot perfectly.",
  "This is a deeply quiet, beautiful book that completely maps the characters' internal emotional landscapes onto the stark, silent external world around them. The prose is so tactile and direct that you can practically feel the cold wind and hear the silence of the woods as you read. It deals with some really heavy themes of isolation, loss, and the struggle to find meaning when everything around you feels chaotic, but it does so with such absolute precision and grace. There is no moralizing, no preachy conclusions, just a direct, wise, and deeply observational look at how we survive the quietest storms of our lives. It reminded me a lot of classic existential literature, but with a modern, grounding warmth that makes it incredibly comforting to read. If you appreciate slow-burn stories that focus on depth, atmosphere, and character psychology rather than fast-paced plots, this is a masterpiece. It really made me appreciate the value of slow living, nature observation, and just being comfortable with silence. Highly, highly recommended.",
  "I've read a lot of books in this space, but this one is on a completely different level. It completely redefines how we think about habits, personal growth, and daily routines. The author's central thesis is that we don't rise to the level of our goals, but instead fall to the level of our systems—which sounds simple, but the way it's unpacked with real-world psychology and deeply personal stories is life-changing. What makes it so special is how casual and humble the delivery is. It feels beneran like having a deep conversation at a coffee shop with someone who has actually been in the trenches and figured out how to build a realistic, balanced life. It covers everything from the friction of starting new habits to the power of tiny, consistent choices that compound over time. It's smart, incredibly wise, and completely free of the toxic positivity that ruins most self-help books. If you are trying to build better systems for your work, your health, or your peace of mind, stop what you are doing and read this book immediately."
];

const r1984 = "Read this in school and completely missed the point—back then it just felt like another dry homework assignment about some grey, depressing future. But reading it again years later? Oh man, it hits completely different. It actually gave me chills because Orwell basically predicted the exact mechanics of modern digital manipulation. We're not talking about some sci-fi world with laser guns; we're talking about the slow, silent death of truth. The way the Party rewrites history every single day until people literally forget what happened yesterday is terrifyingly similar to how our internet algorithms rewrite the narrative in real-time. Orwell shows you that the scariest thing about totalitarianism isn't the physical violence, but the psychological surrender—when people willingly choose comfortable, state-approved lies over hard, uncomfortable truths because it's just easier to survive. You see Winston desperately clinging to his diary, trying to prove to himself that his memory of the past is real, and it makes you realize how fragile our shared reality actually is. If you control the past, you control the future; and if you control the present, you control the past. That sentence used to sound like a catchy slogan, but now it feels like a daily warning about the feeds we consume. The scariest part of the book isn't the bleakness of Room 101 or the torture; it's how Winston eventually learns to love Big Brother, showing that the system's ultimate victory is when it destroys your capacity to even want to be free. It is an absolutely essential read, not just as a classic, but as a map for keeping your own mind alive in an age of constant noise.";

const rAnimalFarm = "This is hands down the most incredibly efficient book I've ever read in my entire life. It is thin enough to finish in a single afternoon over a couple of cups of coffee, but the raw weight of its meaning stays with you for decades. Orwell is an absolute genius because he takes the massive, complex history of the Russian Revolution and the betrayal of socialist ideals, and distils it into a simple, devastatingly clear fable about farm animals. It starts with so much hope—the animals throwing off the human farmer, dreaming of a cooperative utopia where everyone works according to their ability and shares the rewards equally. But then, almost imperceptibly, the power dynamics shift. The pigs, who are the smartest, slowly start taking extra milk and apples, justifying it as 'brainwork.' Orwell tracks the slow, insidious corruption of language so perfectly. The seven commandments written on the barn wall are quietly altered one by one in the dead of night to justify the pigs' privileges, culminating in the famous, chilling line: 'All animals are equal, but some are more equal than others.' It is a masterclass in how revolutions are hijacked by the very people who claim to lead them. You laugh at the absurdity of the pigs wearing human clothes and drinking beer, and then the final sentence hits you like a truck—looking from pig to man, and from man to pig, and it's already impossible to say which is which. It makes you deeply cynical but also incredibly wise about how power works. There is zero fluff, zero wasted words, just a pure, raw mirror held up to human political ambition. Absolutely brilliant.";

const rTotalitarianism = "Okay, let's be real—this book is absolutely heavy and requires some serious mental stamina, but it is hands down one of the most necessary, life-altering works you will ever read. Hannah Arendt is a force of nature. She isn't interested in writing a simple historical account of monsters or dictators; instead, she does a deep, brilliant autopsy of the societal conditions that allowed totalitarianism to rise in the 20th century. What blew my mind is how she explains that totalitarianism doesn't start with physical violence or tanks in the streets. No, it grows silently from deep, systemic emptiness—from a population that has become completely isolated, exhausted, politically homeless, and spiritually lonely. When people are atomized and lose their sense of community and shared truth, they become highly susceptible to propaganda that offers them a single, simple, logically consistent lie to explain all their suffering. Arendt shows that the ideal subject of totalitarian rule is not the convinced Nazi or the convinced Communist, but people for whom the distinction between fact and fiction, and the distinction between true and false, no longer exist. It makes you look at our current landscape of echo chambers, disinformation, and social isolation in a completely new, terrifying light. It is direct, uncompromisingly wise, and deeply observational without trying to moralize or sound preachy. If you want to understand the psychological currents running underneath modern global politics, you absolutely have to sit down and read this. It's a demanding commitment, but the intellectual payoff is massive.";

let updatedCount = 0;
let genericCount = 0;

books.forEach((book, idx) => {
  if (book.id === 'p3') {
    book.review = r1984;
    updatedCount++;
  } else if (book.id === 'p4') {
    book.review = rAnimalFarm;
    updatedCount++;
  } else if (book.id === 'p5') {
    book.review = rTotalitarianism;
    updatedCount++;
  } else if (book.review && (
    book.review.includes("The author constructs a slow, tactile atmosphere") ||
    book.review.includes("A brilliant piece of narrative architecture") ||
    book.review.includes("The prose reads with a beautiful velocity") ||
    book.review.includes("There is a deep, quiet melancholy running through") ||
    book.review.includes("It is written with direct structural confidence")
  )) {
    // Distribute long reviews rotationally
    book.review = longReviews[genericCount % longReviews.length];
    genericCount++;
    updatedCount++;
  }
});

fs.writeFileSync(booksJsonPath, JSON.stringify(books, null, 2), 'utf8');
console.log(`Successfully updated ${updatedCount} books reviews! (Specifics: 3, Generics: ${genericCount})`);
